/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_eoe_usingndk_UsingNDK */

#ifndef _Included_cn_eoe_usingndk_UsingNDK
#define _Included_cn_eoe_usingndk_UsingNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_eoe_usingndk_UsingNDK
 * Method:    getNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_eoe_usingndk_UsingNDK_getNum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
